# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Daglar Duman's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Daglar Duman
headline: Mechatronics Engineer
description: >- # dont remove this line. this will ignore all new lines until the next section
  4th grade Mechatronics student with strong programming skills and passion for robotics, 
  seeking impactful opportunities in a dynamic team environment.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: https://drive.google.com/file/d/1lNEwO062XAjYOgHTHNr1qUer789RtN3C/view?usp=sharing


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: daglarduman    # https://www.linkedin.com/in/{your url slug} 
  github: daglar510    # https://github.com/{your url slug} 
  stackoverflow:      # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Programming Languages
    tools:
      - Python
      - JavaScript
      - Java
      - C++
      - C#
      - C
      - Kotlin
      - SQL
      - Lua

  - category: Frameworks & Libraries
    tools:
      - Django
      - Flask
      - NodeJS
      - ExpressJS
      - Apache Airflow
      - Celery
      - Pandas
      - Unity
      - Godot
      - Elasticsearch
      - Forms
      - GitHub Copilot

  - category: Tools & Technologies
    tools:
      - AWS
      - Docker
      - DataBricks
      - ROS (Robot Operating System)
      - Ansys
      - MATLAB
      - SolidWorks
      - Fusion 360
      - Eagle CAD
      - Arduino
      - Raspberry Pi
      - MongoDB
      - WooCommerce
      - WordPress
      - Jira
      - Git
      - GitHub
      - FileZilla
      - Stripe
      - UiPath
      - IT Automation
      - Emerging Tech
      - Serverless
      - Storage

  - category: Hardware & Embedded Systems
    tools:
      - PCB Design
      - 3D Printing
      - Sensor Integration (IMU, RGB Proximity Sensors, Vibration Sensors)
      - Power Electronics
      - Motor Control (Arduino Due Motor Shield)
      - Microcontroller Programming (CH341)
      - Mechatronic Diagnosis
      - Soldering & Iron Stitching
      - Drone Piloting
      - UAV

  - category: Data Science & Machine Learning
    tools:
      - ETL Pipelines
      - Data Analysis
      - Machine Learning Model Deployment
      - Predictive Maintenance
      - Big Data Processing
      - Workflow Automation
      - SQL Optimization
      - Condition Monitoring
      - Data Visualization
      - AI

  - category: Game Development
    tools:
      - GameGuru Engine
      - Unity Game Engine
      - Blender
      - Android Mobile Game Development

  - category: Web Development & APIs
    tools:
      - Back-end Development
      - API Development
      - Web Scraping
      - Content Management Systems (WordPress/WooCommerce)

  - category: Soft Skills
    tools:
      - Team Leadership (Head of Electrical & Mechanical Departments)
      - Task Management
      - Technical Documentation
      - Workshop Facilitation (Arduino & Python Seminars)
      - Problem-Solving
      - Digital Transformation Initiatives
      - Project Management
      - Startup Development
      - Startups
      - Entrepreneurship

  - category: Programming Concepts
    tools:
      - Concurrent Programming
      - Parallel Computing
      - Syntax
      - Algorithms
      - Compiler Construction


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:  xvgzezjv


# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"


#nofucking clue
colors:
  text: "#1a1c20"
  border: "#e0e7ff"
  link: "#6366f1"
  highlight: "#4f46e5"
  background: "#ffffff"
  light_background: "#f8fafc"



#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/
    sort_by: date
    sort_order: descending


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
